#controllers:
##    resource:
##        path: ../../src/Controller/
##        namespace: App\Controller
#    resource: App\Controller
#    type: attribute
#
#kernel:
#    resource: App\Kernel
#    type: attribute